.TH "CAN\-ETH\-GW" "7" "July 31, 2014" "CAN \- Ethernet Gateway Kernel Module" "master\-preview"
.SH NAME
.PP
ce_gw \- CAN \- Ethernet Gateway Kernel Module
.SH DESCRIPTION
.PP
Module for creating virtual ethernet devices.
These virtual ethernet can transform the message for sending it to a CAN
device and vice\-versa.
See Control Uitlity (cegwctl) for configuring it.
.SH BUGS
.PP
This is an early preview version.
They are maybe some bugs.
Please report bugs at GitHub can_eth_gw
Issues (https://github.com/can-eth-gw/can_eth_gw/issues)
.SH COPYRIGHT
.PP
© Copyright 2013 Fabian Raab, Stefan Smarzly
.PP
This file is part of CAN\-Eth\-GW.
.PP
CAN\-Eth\-GW is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.
.PP
CAN\-Eth\-GW is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along
with CAN\-Eth\-GW.
If not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.PP
\f[B]HOMEPAGE:\f[] can\-eth\-gw.github.io (http://can-eth-gw.github.io/)
.PP
cegwctl(8)
.SH AUTHORS
Fabian Raab <fabian.raab@tum.de>; Stefan Smarzly <stefan.smarzly@in.tum.de>.
